### ISSUE TITLE
[bug] Call to ethereum/transaction/count causes HTTP 500 error

### ISSUE THREAD

**Issue by npwork** [tatumio/tatum-blockchain-connector#118]
ENV: testnet

Request
`{{url}}/ethereum/transaction/count/0x44373FD089C81a5F4634F655cb73598B0E2F7799`

When running this request multiple times error happens.

Response JSON:
```
{
    "statusCode": 500,
    "message": "Internal server error. Returned error: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:9090: connect: connection refused\""
}
```

**Comment by fagunbhavsar** [comment]
Not a bug! the correct URL for above endpoint is - {{url}}/v3/ethereum/transaction/count/0x44373FD089C81a5F4634F655cb73598B0E2F7799

Could you please try the mentioned URL and let us know? Right now, I have checked and it returns "0" as response

**Comment by npwork** [comment]
<img width="1038" alt="Screenshot 2021-12-14 at 11 59 10" src="https://user-images.githubusercontent.com/1792720/145976162-994e03df-208e-4f41-bd69-8902ed036d3a.png">

Try to send requests multiple times

**Comment by npwork** [comment]
@fagunbhavsar I mean send request (click send) 3-5 times quickly

**Comment by fagunbhavsar** [comment]
@npwork thanks for the details. We will look into this to fix. Thanks once again!

**Comment by npwork** [comment]
fixed
